# Libraries

In [27]:
import pickle
import pandas as pd
pd.set_option('display.max_columns', None)
import re
import unicodedata

# Read dataset

In [28]:
df = pd.read_excel('data_models_rv2.xlsx', sheet_name='Dataset_2')
def clean_column_name(name):
    name = unicodedata.normalize('NFKD', str(name)).encode('ASCII', 'ignore').decode('ASCII')
    name = name.lower()
    name = name.replace(' ', '_')
    name = re.sub(r'[^\w_]', '', name)
    name = re.sub(r'__+', '_', name)
    name = name.strip('_')
    return name
df.columns = [clean_column_name(col) for col in df.columns]

# Clean dataset

In [29]:
df.drop(['autor', 'output_w_exp_mm', 'fib_model_code_2020_mm', 'fib_model_code_2020_com_ts_variavel_mm', 'wexp_menos_wfib2020ts'], inplace=True, axis=1)
df.head()

,diametro_da_armadura_mm,resistencia_do_aco_fy_mpa,resistencia_a_tracao_do_concreto_mpa,cobrimento_mm,distancia_ao_centro_de_gravidade_da_armadura_mm,area_de_aco_tracionada_as_mm2,taxa_de_armadura_conforme_mc2020,tensao_na_armadura_menos_tension_stiffening_variavel_mpa,fib_model_code_2010,eurocode_2,nbr_6118_wk1_fissuracao_estabilizada,nbr_6118_wk2_fissuracao_nao_estabilizada,clark_1956,desayiganesan_1985,oh_kang_1987,caldas_1997,gergely_e_lutz_1968,equacao_15_do_artigo_de_belarbi_e_hsu_1994,beta_conforme_fields_e_bischoff_2004,slip_de_yuan_et_al_2025,slip_de_biscaia_e_soares_2020,wexp_menos_wfib2020
0,20.0,500,4.120341,25.0,39.0,628.0,0.0213,120.527746,0.125734,0.125292,0.262468,0.157380,0.181006,0.312684,0.185969,0.129998,0.241528,0.149956,0.116566,0.109686,0.082007,0.073841
1,20.0,500,4.120341,25.0,39.0,628.0,0.0213,223.847983,0.176982,0.176359,0.344489,0.271111,0.244363,0.410398,0.256204,0.174746,0.317005,0.204348,0.197288,0.193326,0.156266,0.082873
2,20.0,500,4.120341,25.0,39.0,628.0,0.0213,242.052198,0.184078,0.183430,0.355846,0.289281,0.253135,0.423928,0.265928,0.180941,0.327456,0.212052,0.208041,0.205301,0.167096,0.084432
3,20.0,500,4.120341,25.0,39.0,628.0,0.0213,325.147190,0.218769,0.217999,0.411368,0.386596,0.296022,0.490072,0.313472,0.211232,0.378549,0.250139,0.259368,0.265222,0.221958,0.073162
4,20.0,500,4.120341,25.0,39.0,628.0,0.0213,447.784457,0.286574,0.285566,0.519888,0.617471,0.379848,0.619355,0.406398,0.270437,0.478411,0.311870,0.354810,0.388948,0.338382,0.072498

In [30]:
x = df.drop('wexp_menos_wfib2020', axis=1)
x.head()

,diametro_da_armadura_mm,resistencia_do_aco_fy_mpa,resistencia_a_tracao_do_concreto_mpa,cobrimento_mm,distancia_ao_centro_de_gravidade_da_armadura_mm,area_de_aco_tracionada_as_mm2,taxa_de_armadura_conforme_mc2020,tensao_na_armadura_menos_tension_stiffening_variavel_mpa,fib_model_code_2010,eurocode_2,nbr_6118_wk1_fissuracao_estabilizada,nbr_6118_wk2_fissuracao_nao_estabilizada,clark_1956,desayiganesan_1985,oh_kang_1987,caldas_1997,gergely_e_lutz_1968,equacao_15_do_artigo_de_belarbi_e_hsu_1994,beta_conforme_fields_e_bischoff_2004,slip_de_yuan_et_al_2025,slip_de_biscaia_e_soares_2020
0,20.0,500,4.120341,25.0,39.0,628.0,0.0213,120.527746,0.125734,0.125292,0.262468,0.157380,0.181006,0.312684,0.185969,0.129998,0.241528,0.149956,0.116566,0.109686,0.082007
1,20.0,500,4.120341,25.0,39.0,628.0,0.0213,223.847983,0.176982,0.176359,0.344489,0.271111,0.244363,0.410398,0.256204,0.174746,0.317005,0.204348,0.197288,0.193326,0.156266
2,20.0,500,4.120341,25.0,39.0,628.0,0.0213,242.052198,0.184078,0.183430,0.355846,0.289281,0.253135,0.423928,0.265928,0.180941,0.327456,0.212052,0.208041,0.205301,0.167096
3,20.0,500,4.120341,25.0,39.0,628.0,0.0213,325.147190,0.218769,0.217999,0.411368,0.386596,0.296022,0.490072,0.313472,0.211232,0.378549,0.250139,0.259368,0.265222,0.221958
4,20.0,500,4.120341,25.0,39.0,628.0,0.0213,447.784457,0.286574,0.285566,0.519888,0.617471,0.379848,0.619355,0.406398,0.270437,0.478411,0.311870,0.354810,0.388948,0.338382

In [31]:
y = df['wexp_menos_wfib2020'].to_frame()
y.head()

   wexp_menos_wfib2020
0             0.073841
1             0.082873
2             0.084432
3             0.073162
4             0.072498

# Pickle data

In [32]:
data_pickle = [{'metadados': 'index [1] contain independent variables (x), index [2] contain dependent variables (y)'}, x, y]

In [33]:
filename = f'dataset_2.pkl'
with open(filename, 'wb') as f:
    pickle.dump(data_pickle, f)