# Libraries

In [1]:
import pickle
import pandas as pd
import numpy as np
import unicodedata
import re
pd.set_option('display.max_columns', None)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score
from pysr import PySRRegressor
import matplotlib.pyplot as plt
import itertools
import os

Detected IPython. Loading juliacall extension. See https://juliapy.github.io/PythonCall.jl/stable/compat/#IPython

# Read dataset

In [2]:
filename = '../../dataset/dataset_2_rv3.xlsx'
dataset = pd.read_excel(filename)
def clean_column_name(name):
    name = unicodedata.normalize('NFKD', str(name)).encode('ASCII', 'ignore').decode('ASCII')
    name = name.lower()
    name = name.replace(' ', '_')
    name = re.sub(r'[^\w_]', '', name)
    name = re.sub(r'__+', '_', name)
    name = name.strip('_')
    return name
dataset.columns = [clean_column_name(col) for col in dataset.columns]

In [3]:
x = dataset[[
                'diametro_da_armadura_mm', 'resistencia_do_aco_fy_mpa',
                'resistencia_a_tracao_do_concreto_mpa', 'cobrimento_mm',
                'taxa_de_armadura_conforme_mc2020',
                'tensao_na_armadura_menos_tension_stiffening_variavel_mpa',
                'fib_model_code_2010', 'eurocode_2',
                'nbr_6118_wk1_fissuracao_estabilizada',
                'nbr_6118_wk2_fissuracao_nao_estabilizada', 'clark_1956',
                'desayiganesan_1985', 'oh_kang_1987', 'caldas_1997',
                'gergely_e_lutz_1968', 'equacao_15_do_artigo_de_belarbi_e_hsu_1994',
                'beta_conforme_fields_e_bischoff_2004', 'slip_de_yuan_et_al_2025',
                'slip_de_biscaia_e_soares_2020'
            ]]  
x.head()

,diametro_da_armadura_mm,resistencia_do_aco_fy_mpa,resistencia_a_tracao_do_concreto_mpa,cobrimento_mm,taxa_de_armadura_conforme_mc2020,tensao_na_armadura_menos_tension_stiffening_variavel_mpa,fib_model_code_2010,eurocode_2,nbr_6118_wk1_fissuracao_estabilizada,nbr_6118_wk2_fissuracao_nao_estabilizada,clark_1956,desayiganesan_1985,oh_kang_1987,caldas_1997,gergely_e_lutz_1968,equacao_15_do_artigo_de_belarbi_e_hsu_1994,beta_conforme_fields_e_bischoff_2004,slip_de_yuan_et_al_2025,slip_de_biscaia_e_soares_2020
0,20.0,500,4.120341,25.0,0.0213,120.527746,0.125734,0.125292,0.262468,0.157380,0.181006,0.312684,0.246013,0.129998,0.241528,0.149956,0.116566,0.109686,0.082007
1,20.0,500,4.120341,25.0,0.0213,223.847983,0.176982,0.176359,0.344489,0.271111,0.244363,0.410398,0.338924,0.174746,0.317005,0.204348,0.197288,0.193326,0.156266
2,20.0,500,4.120341,25.0,0.0213,242.052198,0.184078,0.183430,0.355846,0.289281,0.253135,0.423928,0.351788,0.180941,0.327456,0.212052,0.208041,0.205301,0.167096
3,20.0,500,4.120341,25.0,0.0213,325.147190,0.218769,0.217999,0.411368,0.386596,0.296022,0.490072,0.414682,0.211232,0.378549,0.250139,0.259368,0.265222,0.221958
4,20.0,500,4.120341,25.0,0.0213,447.784457,0.286574,0.285566,0.519888,0.617471,0.379848,0.619355,0.537611,0.270437,0.478411,0.311870,0.354810,0.388948,0.338382

In [4]:
y = dataset[['wexp_menos_wfib2020ts']]
y.head()

   wexp_menos_wfib2020ts
0               0.057870
1               0.039217
2               0.036942
3               0.006931
4              -0.030363

# Symbolic Regression

### Grid Search parameters

In [5]:
size_test = 0.2                             # Proportion of the dataset to include in the test split

In [6]:
n_folds = 10                                # Number of folds for cross-validation
parsimony_levels = [0.001, 0.01]            # Regularization levels to control model complexity
max_size_levels = [20, 30]                  # Maximum size of the equations
pop_size_levels = [250, 500]                # Population size for the evolutionary algorithm
ncycles_per_iteration_levels = [1000]       # Number of cycles per iteration
niterations_levels = [500]                  # Number of iterations
weight_optimize_levels = [0.001]            # Weight optimization levels

In [7]:
combs_ = list(itertools.product(parsimony_levels, max_size_levels, pop_size_levels, ncycles_per_iteration_levels, niterations_levels, weight_optimize_levels))
da = pd.DataFrame(combs_, columns=['parsimony', 'max_size', 'pop_size', 'ncycles_per_iteration', 'niterations', 'weight_optimize'])
da

,parsimony,max_size,pop_size,ncycles_per_iteration,niterations,weight_optimize
0,0.001,20,250,1000,500,0.001
1,0.001,20,500,1000,500,0.001
2,0.001,30,250,1000,500,0.001
3,0.001,30,500,1000,500,0.001
4,0.010,20,250,1000,500,0.001
5,0.010,20,500,1000,500,0.001
6,0.010,30,250,1000,500,0.001
7,0.010,30,500,1000,500,0.001

### Train and Test

In [8]:
dx = []
for j in range(n_folds):
   # Split the data in training and testing sets
   x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=size_test)
   # Standardize the features using StandardScaler z-score normalization
   scaler = StandardScaler()
   scaler.fit(x_train)
   x_train_scaled = scaler.transform(x_train)
   x_train_scaled = pd.DataFrame(x_train_scaled, columns=x.columns)
   x_test_scaled = scaler.transform(x_test)
   x_test_scaled = pd.DataFrame(x_test_scaled, columns=x.columns)
   
   for i, row in da.iterrows():
      # Save the scaler parameters
      dict_res = {}
      for i, col_name in enumerate(x_train.columns):
         dict_res[col_name] = {"avg": scaler.mean_[i], "std_dev": scaler.scale_[i]}
      
      # Train the PySR model
      model = PySRRegressor(
                              parsimony=row['parsimony'],           
                              maxsize=int(row['max_size']),
                              maxdepth=30,
                              population_size=int(row['pop_size']),
                              ncycles_per_iteration=int(row['ncycles_per_iteration']),
                              niterations=int(row['niterations']), 
                              adaptive_parsimony_scaling=50,
                              deterministic=False, 
                              should_optimize_constants=True,
                              optimizer_algorithm="BFGS",
                              optimizer_nrestarts=3,
                              binary_operators=["+", "-", "*", "/"],
                              unary_operators=["sin", "cos", "exp", "sqrt", "log", "abs", "square", "cube"],
                              weight_optimize=row['weight_optimize'],
                              verbosity=0,
                              progress=False,
                              parallelism='multithreading',
                              early_stop_condition=1e-8,
                           )
      model.fit(x_train_scaled, y_train)
      
      # Statistics and results
      y_pred_train = model.predict(x_train_scaled)
      y_pred_test = model.predict(x_test_scaled)
      rmse_train = np.sqrt(mean_squared_error(y_train, y_pred_train))
      rmse_test = np.sqrt(mean_squared_error(y_test, y_pred_test))
      r2_train = r2_score(y_train, y_pred_train)
      r2_test = r2_score(y_test, y_pred_test)
      print(f"Train RMSE: {rmse_train}")
      print(f"Test RMSE: {rmse_test}")
      print(f"Train R2: {r2_train}")
      print(f"Test R2: {r2_test}")
      best_eq = model.get_best()
      best_equation = best_eq['equation']
      print(f"Best Equation: {best_equation}")
      print("\n\n")
      dict_res['model'] = {
                              "train_rmse": rmse_train,
                              "test_rmse": rmse_test,
                              "train_r2": r2_train,
                              "test_r2": r2_test,
                              "best_equation": best_equation,
                              "scaler_params": scaler,
                              "model_object": model
                          }
      dx.append(dict_res)

Train RMSE: 0.053994735793867335
Test RMSE: 0.0637451442859482
Train R2: 0.6475155718323629
Test R2: 0.391875605323431
Best Equation: (((tensao_na_armadura_menos_tension_stiffening_variavel_mpa + (eurocode_2 / 0.57883465)) - slip_de_biscaia_e_soares_2020) - caldas_1997) * -0.056128457



Train RMSE: 0.05399473565577435
Test RMSE: 0.06374538837733769
Train R2: 0.6475155736353397
Test R2: 0.39187094808359446
Best Equation: (eurocode_2 - (((caldas_1997 + slip_de_biscaia_e_soares_2020) - tensao_na_armadura_menos_tension_stiffening_variavel_mpa) * 0.5788262)) * -0.09696948



Train RMSE: 0.0539947357375041
Test RMSE: 0.0637466993969169
Train R2: 0.6475155725682555
Test R2: 0.39184593365313714
Best Equation: ((tensao_na_armadura_menos_tension_stiffening_variavel_mpa + ((eurocode_2 / 0.57878894) - slip_de_biscaia_e_soares_2020)) - caldas_1997) * -0.05612994



Train RMSE: 0.05399473507667842
Test RMSE: 0.06374593409258014
Train R2: 0.6475155811961617
Test R2: 0.39186053582564206
Best Equation: (((caldas_1997 + slip_de_biscaia_e_soares_2020) - tensao_na_armadura_menos_tension_stiffening_variavel_mpa) * 0.056123294) + (eurocode_2 * -0.09696889)



Train RMSE: 0.05399473505301045
Test RMSE: 0.06374630966373543
Train R2: 0.6475155815051767
Test R2: 0.3918533698685587
Best Equation: (((tensao_na_armadura_menos_tension_stiffening_variavel_mpa + (eurocode_2 * 1.727865)) - caldas_1997) - slip_de_biscaia_e_soares_2020) * -0.056120902



Train RMSE: 0.05399473503343262
Test RMSE: 0.06374605447689835
Train R2: 0.6475155817607898
Test R2: 0.3918582388783953
Best Equation: (eurocode_2 * -0.096968055) + (((tensao_na_armadura_menos_tension_stiffening_variavel_mpa - slip_de_biscaia_e_soares_2020) - caldas_1997) * -0.05612119)



Train RMSE: 0.05177898046118189
Test RMSE: 0.05082060460680387
Train R2: 0.6758514489994429
Test R2: 0.6134747556766346
Best Equation: ((cos(resistencia_a_tracao_do_concreto_mpa) * (caldas_1997 - tensao_na_armadura_menos_tension_stiffening_variavel_mpa)) + ((slip_de_yuan_et_al_2025 * 0.6116233) - eurocode_2)) * 0.08163473



Train RMSE: 0.053994735144053625
Test RMSE: 0.0637460056496681
Train R2: 0.6475155803164941
Test R2: 0.3918591705083342
Best Equation: ((((slip_de_biscaia_e_soares_2020 + caldas_1997) - tensao_na_armadura_menos_tension_stiffening_variavel_mpa) / 1.7278925) - eurocode_2) * 0.096965104



Train RMSE: 0.05128844047149218
Test RMSE: 0.059823913940509954
Train R2: 0.6673571553083203
Test R2: 0.5655532168365864
Best Equation: (slip_de_biscaia_e_soares_2020 - (sin(((-0.12221581 / cobrimento_mm) + tensao_na_armadura_menos_tension_stiffening_variavel_mpa) * cos(resistencia_do_aco_fy_mpa)) + eurocode_2)) * 0.10738001



Train RMSE: 0.05128844062534719
Test RMSE: 0.059823911711815426
Train R2: 0.6673571533125969
Test R2: 0.5655532492065564
Best Equation: (sin(cos(resistencia_do_aco_fy_mpa) * ((0.12225202 / cobrimento_mm) - tensao_na_armadura_menos_tension_stiffening_variavel_mpa)) + (slip_de_biscaia_e_soares_2020 - eurocode_2)) * 0.107393205



Train RMSE: 0.0446621942947018
Test RMSE: 0.05467825326433665
Train R2: 0.7477568903445168
Test R2: 0.6370755692641168
Best Equation: (((((cos(slip_de_biscaia_e_soares_2020 + (square(tensao_na_armadura_menos_tension_stiffening_variavel_mpa - beta_conforme_fields_e_bischoff_2004) - nbr_6118_wk1_fissuracao_estabilizada)) + eurocode_2) + nbr_6118_wk1_fissuracao_estabilizada) - caldas_1997) - ((oh_kang_1987 - tensao_na_armadura_menos_tension_stiffening_variavel_mpa) * 1.5711042)) * -0.055159096) + 0.020215385



Train RMSE: 0.047925990839939196
Test RMSE: 0.046925145351372495
Train R2: 0.7095432995758653
Test R2: 0.7327004714279972
Best Equation: (((cos(exp(resistencia_a_tracao_do_concreto_mpa / 0.18477844)) * (tensao_na_armadura_menos_tension_stiffening_variavel_mpa - caldas_1997)) + eurocode_2) - (oh_kang_1987 / 1.5225667)) * -0.08979672



Train RMSE: 0.06073906715655303
Test RMSE: 0.06397767408057223
Train R2: 0.5334744495596739
Test R2: 0.5031287891045069
Best Equation: ((slip_de_biscaia_e_soares_2020 - sin(tensao_na_armadura_menos_tension_stiffening_variavel_mpa)) - eurocode_2) * 0.0799776



Train RMSE: 0.055628714378812255
Test RMSE: 0.05964162574704978
Train R2: 0.6086753143579764
Test R2: 0.5681967704949694
Best Equation: (slip_de_biscaia_e_soares_2020 - (eurocode_2 + sin(cos(resistencia_do_aco_fy_mpa) * tensao_na_armadura_menos_tension_stiffening_variavel_mpa))) * 0.09954733



Train RMSE: 0.052231444554873406
Test RMSE: 0.05104995793993128
Train R2: 0.6550125686440732
Test R2: 0.6836428044362532
Best Equation: (((cos(resistencia_a_tracao_do_concreto_mpa) * (caldas_1997 - tensao_na_armadura_menos_tension_stiffening_variavel_mpa)) + (slip_de_yuan_et_al_2025 * 0.67365456)) - eurocode_2) * 0.081175394



Train RMSE: 0.04980797807661596
Test RMSE: 0.06557751890456988
Train R2: 0.6862837442314303
Test R2: 0.47796826833243
Best Equation: ((abs(clark_1956 - (equacao_15_do_artigo_de_belarbi_e_hsu_1994 / 0.7109946)) + (sin(oh_kang_1987 - tensao_na_armadura_menos_tension_stiffening_variavel_mpa) - clark_1956)) * 0.07126248) + -0.04817572



Train RMSE: 0.060332785548451284
Test RMSE: 0.06279356160949147
Train R2: 0.526979015804482
Test R2: 0.5761463492870529
Best Equation: (sin(tensao_na_armadura_menos_tension_stiffening_variavel_mpa) + (eurocode_2 - slip_de_biscaia_e_soares_2020)) * -0.07727712



Train RMSE: 0.05626571115075664
Test RMSE: 0.055336116249122894
Train R2: 0.5886028507024733
Test R2: 0.6708430382937067
Best Equation: ((tensao_na_armadura_menos_tension_stiffening_variavel_mpa + ((eurocode_2 * 1.7682382) - slip_de_biscaia_e_soares_2020)) - caldas_1997) * -0.050169803



Train RMSE: 0.054009588460550546
Test RMSE: 0.06067390654986879
Train R2: 0.6209335138741936
Test R2: 0.6042785320053354
Best Equation: (((eurocode_2 + tensao_na_armadura_menos_tension_stiffening_variavel_mpa) - slip_de_biscaia_e_soares_2020) * -0.07402275) + ((caldas_1997 + resistencia_a_tracao_do_concreto_mpa) * 0.02799016)



Train RMSE: 0.04350537715068787
Test RMSE: 0.048678035707353594
Train R2: 0.754042806337504
Test R2: 0.745286604856781
Best Equation: (((eurocode_2 - ((slip_de_biscaia_e_soares_2020 * 1.2820576) - tensao_na_armadura_menos_tension_stiffening_variavel_mpa)) * -0.09514477) + -0.041293778) + ((resistencia_a_tracao_do_concreto_mpa + (caldas_1997 + exp((resistencia_do_aco_fy_mpa - cos(nbr_6118_wk1_fissuracao_estabilizada - eurocode_2)) - -0.84108096))) * 0.020993385)



Train RMSE: 0.05626571115377565
Test RMSE: 0.055336006617766664
Train R2: 0.5886028506583253
Test R2: 0.67084434253733
Best Equation: ((((slip_de_biscaia_e_soares_2020 - tensao_na_armadura_menos_tension_stiffening_variavel_mpa) + caldas_1997) * 0.5655374) - eurocode_2) * 0.08871221



Train RMSE: 0.056668493644948296
Test RMSE: 0.05798357484103713
Train R2: 0.5826917312132066
Test R2: 0.638593741215828
Best Equation: ((slip_de_biscaia_e_soares_2020 - eurocode_2) - sin(cos(resistencia_do_aco_fy_mpa) * tensao_na_armadura_menos_tension_stiffening_variavel_mpa)) * 0.09395277



Train RMSE: 0.05300462045677739
Test RMSE: 0.05457850199205833
Train R2: 0.6349090131993324
Test R2: 0.6797944037724473
Best Equation: ((eurocode_2 - ((caldas_1997 - tensao_na_armadura_menos_tension_stiffening_variavel_mpa) - (nbr_6118_wk1_fissuracao_estabilizada * 0.56512266))) - oh_kang_1987) * -0.069293596



Train RMSE: 0.04430867903510475
Test RMSE: 0.047725680250635595
Train R2: 0.7448760333354737
Test R2: 0.7551557274510035
Best Equation: (((cos(((resistencia_a_tracao_do_concreto_mpa + cube(resistencia_do_aco_fy_mpa)) * 0.6504051) + cobrimento_mm) * -0.04132785) + (oh_kang_1987 * 0.015517618)) * (slip_de_biscaia_e_soares_2020 + 1.6628404)) - (eurocode_2 * 0.06475484)



Train RMSE: 0.05428467933492545
Test RMSE: 0.061822377582178276
Train R2: 0.6556967057635691
Test R2: 0.3535773300226873
Best Equation: -0.05805017 * (((eurocode_2 / 0.6055684) + (tensao_na_armadura_menos_tension_stiffening_variavel_mpa - caldas_1997)) - slip_de_biscaia_e_soares_2020)



Train RMSE: 0.054284678240767215
Test RMSE: 0.06182048330035808
Train R2: 0.6556967196430756
Test R2: 0.3536169431207242
Best Equation: (((caldas_1997 + (slip_de_biscaia_e_soares_2020 - tensao_na_armadura_menos_tension_stiffening_variavel_mpa)) / 1.6512842) - eurocode_2) * 0.09584746



Train RMSE: 0.049848775486935545
Test RMSE: 0.05816721230615568
Train R2: 0.7096675268812425
Test R2: 0.42775543946872174
Best Equation: (eurocode_2 + (((tensao_na_armadura_menos_tension_stiffening_variavel_mpa - caldas_1997) * cos(resistencia_a_tracao_do_concreto_mpa)) - (slip_de_biscaia_e_soares_2020 / 1.540406))) * -0.08938989



Train RMSE: 0.0500776022358692
Test RMSE: 0.05651321586314688
Train R2: 0.7069959138101689
Test R2: 0.4598365245593268
Best Equation: (eurocode_2 * -0.101963595) - ((((tensao_na_armadura_menos_tension_stiffening_variavel_mpa - caldas_1997) * cos(resistencia_a_tracao_do_concreto_mpa)) - slip_de_biscaia_e_soares_2020) * 0.07067509)



Train RMSE: 0.05428467824067619
Test RMSE: 0.06182048114653836
Train R2: 0.6556967196442303
Test R2: 0.3536169881605711
Best Equation: ((tensao_na_armadura_menos_tension_stiffening_variavel_mpa - (slip_de_biscaia_e_soares_2020 - (eurocode_2 * 1.6512855))) - caldas_1997) * -0.058044136



Train RMSE: 0.05007790784765787
Test RMSE: 0.05652675286103934
Train R2: 0.7069923375296718
Test R2: 0.45957771544762993
Best Equation: (((tensao_na_armadura_menos_tension_stiffening_variavel_mpa - caldas_1997) * cos(resistencia_a_tracao_do_concreto_mpa)) - (slip_de_biscaia_e_soares_2020 - (eurocode_2 * 1.4406588))) * -0.070878595



Train RMSE: 0.04984877546801533
Test RMSE: 0.05816651341104327
Train R2: 0.709667527101635
Test R2: 0.42776919073882447
Best Equation: ((((cos(resistencia_a_tracao_do_concreto_mpa) * (tensao_na_armadura_menos_tension_stiffening_variavel_mpa - caldas_1997)) + eurocode_2) * 1.5403045) - slip_de_biscaia_e_soares_2020) * -0.05803379



Train RMSE: 0.051381793678828426
Test RMSE: 0.06381209367542269
Train R2: 0.6915355310023457
Test R2: 0.31129829162007094
Best Equation: (((taxa_de_armadura_conforme_mc2020 - ((desayiganesan_1985 - caldas_1997) * equacao_15_do_artigo_de_belarbi_e_hsu_1994)) + (equacao_15_do_artigo_de_belarbi_e_hsu_1994 - eurocode_2)) - tensao_na_armadura_menos_tension_stiffening_variavel_mpa) * 0.044226788



Train RMSE: 0.056267363495692
Test RMSE: 0.09507746826130183
Train R2: 0.5768913611041921
Test R2: 0.08677111389722258
Best Equation: (cos(resistencia_do_aco_fy_mpa / 0.0019464097) - eurocode_2) * 0.048590306



Train RMSE: 0.044997585516040745
Test RMSE: 0.06510150577723196
Train R2: 0.7294066105417983
Test R2: 0.571839607220688
Best Equation: ((eurocode_2 - (cos(exp(0.26835757 / sin(cobrimento_mm))) * (caldas_1997 - tensao_na_armadura_menos_tension_stiffening_variavel_mpa))) - (oh_kang_1987 * 0.5259745)) * -0.08924007



Train RMSE: 0.050275159152778276
Test RMSE: 0.06706800580663506
Train R2: 0.6622108708382842
Test R2: 0.5455823314781947
Best Equation: ((oh_kang_1987 - tensao_na_armadura_menos_tension_stiffening_variavel_mpa) - (((nbr_6118_wk2_fissuracao_nao_estabilizada + eurocode_2) - slip_de_yuan_et_al_2025) - (caldas_1997 - eurocode_2))) * 0.04773188



Train RMSE: 0.04868970406251492
Test RMSE: 0.06787402441731483
Train R2: 0.6831796784024688
Test R2: 0.5345943800208628
Best Equation: ((sin(eurocode_2 - caldas_1997) + sin(tensao_na_armadura_menos_tension_stiffening_variavel_mpa - oh_kang_1987)) * -0.10188481) + (nbr_6118_wk1_fissuracao_estabilizada * -0.041204017)



Train RMSE: 0.05634521148504991
Test RMSE: 0.09193474278512527
Train R2: 0.5757197781348637
Test R2: 0.14614573259794483
Best Equation: (sin(resistencia_do_aco_fy_mpa * 423.63272) - eurocode_2) * 0.044674907



Train RMSE: 0.053416900456343425
Test RMSE: 0.06815979559545014
Train R2: 0.6186742534527703
Test R2: 0.5306671192300323
Best Equation: (((oh_kang_1987 + caldas_1997) - tensao_na_armadura_menos_tension_stiffening_variavel_mpa) * 0.05015678) - (eurocode_2 * 0.08943649)



Train RMSE: 0.05087765720026918
Test RMSE: 0.08114076520611316
Train R2: 0.6540662216344422
Test R2: 0.3348759973786932
Best Equation: ((fib_model_code_2010 + eurocode_2) - (cos(resistencia_do_aco_fy_mpa * -973.557) + caldas_1997)) * -0.040484123



Train RMSE: 0.04573497750502754
Test RMSE: 0.06616625341992212
Train R2: 0.7204653169612083
Test R2: 0.5577197865319923
Best Equation: (((tensao_na_armadura_menos_tension_stiffening_variavel_mpa - caldas_1997) * 0.010242805) / sin(cobrimento_mm)) + ((caldas_1997 - (tensao_na_armadura_menos_tension_stiffening_variavel_mpa + ((eurocode_2 * 1.8348423) - oh_kang_1987))) * 0.04685314)



Train RMSE: 0.05258920095069179
Test RMSE: 0.047282230730074475
Train R2: 0.6622528047860796
Test R2: 0.6942240716321224
Best Equation: (((eurocode_2 + ((tensao_na_armadura_menos_tension_stiffening_variavel_mpa - caldas_1997) * cos(resistencia_a_tracao_do_concreto_mpa))) * 1.4508741) - slip_de_yuan_et_al_2025) * -0.05503919



Train RMSE: 0.05416902936938798
Test RMSE: 0.04877443450649452
Train R2: 0.6416555237422172
Test R2: 0.6746192444831063
Best Equation: ((eurocode_2 - ((caldas_1997 + oh_kang_1987) - tensao_na_armadura_menos_tension_stiffening_variavel_mpa)) * -0.073960334) + (nbr_6118_wk1_fissuracao_estabilizada * -0.03565228)



Train RMSE: 0.05180251312507287
Test RMSE: 0.05344500579731222
Train R2: 0.6722820226330849
Test R2: 0.6093195902519708
Best Equation: (sin(nbr_6118_wk2_fissuracao_nao_estabilizada + sin((sin(tensao_na_armadura_menos_tension_stiffening_variavel_mpa) + 0.24157146) - oh_kang_1987)) + (eurocode_2 - slip_de_biscaia_e_soares_2020)) * -0.106466115



Train RMSE: 0.0474154581052037
Test RMSE: 0.046561672501311116
Train R2: 0.7254392145141861
Test R2: 0.7034728106085483
Best Equation: ((nbr_6118_wk1_fissuracao_estabilizada * 0.42271358) + ((eurocode_2 + (cos(square(cube(resistencia_a_tracao_do_concreto_mpa)) / diametro_da_armadura_mm) * (tensao_na_armadura_menos_tension_stiffening_variavel_mpa - caldas_1997))) - oh_kang_1987)) * -0.08224989



Train RMSE: 0.05416902895314427
Test RMSE: 0.04877481279156722
Train R2: 0.6416555292493726
Test R2: 0.6746141972832229
Best Equation: (((oh_kang_1987 + (caldas_1997 - tensao_na_armadura_menos_tension_stiffening_variavel_mpa)) - eurocode_2) * 0.07396115) - (nbr_6118_wk1_fissuracao_estabilizada * 0.035659492)



Train RMSE: 0.0541690293950734
Test RMSE: 0.04877561596514494
Train R2: 0.6416555234023836
Test R2: 0.6746034809558361
Best Equation: (((oh_kang_1987 - tensao_na_armadura_menos_tension_stiffening_variavel_mpa) - (nbr_6118_wk1_fissuracao_estabilizada * 0.4822398)) - (eurocode_2 - caldas_1997)) * 0.07395793



Train RMSE: 0.05132564995440032
Test RMSE: 0.048328019698464904
Train R2: 0.6782878061153863
Test R2: 0.6805481724812418
Best Equation: (sin(tensao_na_armadura_menos_tension_stiffening_variavel_mpa) + (eurocode_2 + (cos(resistencia_do_aco_fy_mpa / 0.007855796) - slip_de_yuan_et_al_2025))) * -0.061415616



Train RMSE: 0.051802512093858374
Test RMSE: 0.05344490189279363
Train R2: 0.672282035680619
Test R2: 0.6093211093245141
Best Equation: (eurocode_2 - (slip_de_biscaia_e_soares_2020 - sin(nbr_6118_wk2_fissuracao_nao_estabilizada - sin(oh_kang_1987 - (sin(tensao_na_armadura_menos_tension_stiffening_variavel_mpa) + 0.24145159))))) * -0.106473275



Train RMSE: 0.05996448070233653
Test RMSE: 0.0671430535047381
Train R2: 0.5619464242213247
Test R2: 0.3787865366749542
Best Equation: (eurocode_2 - (slip_de_biscaia_e_soares_2020 - sin(tensao_na_armadura_menos_tension_stiffening_variavel_mpa))) * -0.084410794



Train RMSE: 0.053857958474378284
Test RMSE: 0.05150024462766173
Train R2: 0.6466225357400128
Test R2: 0.6345253428927522
Best Equation: (nbr_6118_wk1_fissuracao_estabilizada + (((eurocode_2 - (oh_kang_1987 - tensao_na_armadura_menos_tension_stiffening_variavel_mpa)) - caldas_1997) * 1.7719911)) * -0.041583788



Train RMSE: 0.04902254512717077
Test RMSE: 0.050168179766193
Train R2: 0.7072271598832294
Test R2: 0.6531869975666982
Best Equation: (eurocode_2 - (((beta_conforme_fields_e_bischoff_2004 + 1.1999528) - nbr_6118_wk1_fissuracao_estabilizada) * ((caldas_1997 + (oh_kang_1987 + (-0.33869082 - tensao_na_armadura_menos_tension_stiffening_variavel_mpa))) - nbr_6118_wk1_fissuracao_estabilizada))) * -0.046806183



Train RMSE: 0.046010643030234846
Test RMSE: 0.05670120020370597
Train R2: 0.7420974231095094
Test R2: 0.5569801487395208
Best Equation: (((diametro_da_armadura_mm + square(oh_kang_1987 - nbr_6118_wk1_fissuracao_estabilizada)) - (cos(cobrimento_mm) - (equacao_15_do_artigo_de_belarbi_e_hsu_1994 * (caldas_1997 - desayiganesan_1985)))) * 0.030267743) + (eurocode_2 * -0.049319036)



Train RMSE: 0.05996448061380331
Test RMSE: 0.06714239915356453
Train R2: 0.5619464255148336
Test R2: 0.3787986448456967
Best Equation: (sin(tensao_na_armadura_menos_tension_stiffening_variavel_mpa) - (slip_de_biscaia_e_soares_2020 - eurocode_2)) * -0.084407195



Train RMSE: 0.048826783506860066
Test RMSE: 0.05673840366048749
Train R2: 0.7095607494636709
Test R2: 0.5563985992495832
Best Equation: ((slip_de_biscaia_e_soares_2020 - sin(square(-0.20749018 / cobrimento_mm) + (tensao_na_armadura_menos_tension_stiffening_variavel_mpa - ((gergely_e_lutz_1968 + resistencia_a_tracao_do_concreto_mpa) * 0.3144484)))) - eurocode_2) * 0.1055758



Train RMSE: 0.053173819050994504
Test RMSE: 0.05892544301833693
Train R2: 0.6555431843187772
Test R2: 0.5215413659025875
Best Equation: ((eurocode_2 + sin(tensao_na_armadura_menos_tension_stiffening_variavel_mpa + ((resistencia_a_tracao_do_concreto_mpa + equacao_15_do_artigo_de_belarbi_e_hsu_1994) * -0.38866886))) - slip_de_biscaia_e_soares_2020) * -0.10957841



Train RMSE: 0.0492627067735837
Test RMSE: 0.052973645472311114
Train R2: 0.704351542614156
Test R2: 0.6133140391078274
Best Equation: ((((((oh_kang_1987 + caldas_1997) - eurocode_2) - tensao_na_armadura_menos_tension_stiffening_variavel_mpa) + 0.5297381) - cos(nbr_6118_wk1_fissuracao_estabilizada - slip_de_biscaia_e_soares_2020)) - nbr_6118_wk1_fissuracao_estabilizada) * 0.06035093



Train RMSE: 0.059668785530859816
Test RMSE: 0.06635678417885078
Train R2: 0.5118093336938082
Test R2: 0.5956740850785089
Best Equation: (eurocode_2 + (sin(tensao_na_armadura_menos_tension_stiffening_variavel_mpa) - slip_de_biscaia_e_soares_2020)) * -0.07809344



Train RMSE: 0.05966878553541952
Test RMSE: 0.06635677368633293
Train R2: 0.5118093336191961
Test R2: 0.5956742129447579
Best Equation: ((slip_de_biscaia_e_soares_2020 - sin(tensao_na_armadura_menos_tension_stiffening_variavel_mpa)) - eurocode_2) * 0.0780935



Train RMSE: 0.05466064564095011
Test RMSE: 0.060691674292658135
Train R2: 0.5903201637399726
Test R2: 0.6617645268029535
Best Equation: (slip_de_biscaia_e_soares_2020 - (tensao_na_armadura_menos_tension_stiffening_variavel_mpa + ((eurocode_2 / 0.5870976) - caldas_1997))) * 0.053461086



Train RMSE: 0.04650342576991596
Test RMSE: 0.04759593300089792
Train R2: 0.7034725045799921
Test R2: 0.7919821490546184
Best Equation: (((eurocode_2 * 1.742443) - ((caldas_1997 - -0.44962245) * (equacao_15_do_artigo_de_belarbi_e_hsu_1994 - (clark_1956 - 0.5823471)))) - ((oh_kang_1987 - sin(exp(resistencia_a_tracao_do_concreto_mpa))) - tensao_na_armadura_menos_tension_stiffening_variavel_mpa)) * -0.045211125



Train RMSE: 0.059668785402936714
Test RMSE: 0.06635712520742465
Train R2: 0.511809335787059
Test R2: 0.5956699291494303
Best Equation: ((slip_de_biscaia_e_soares_2020 - sin(tensao_na_armadura_menos_tension_stiffening_variavel_mpa)) - eurocode_2) * 0.07809149



Train RMSE: 0.05966878553465699
Test RMSE: 0.06635677543508314
Train R2: 0.5118093336316738
Test R2: 0.5956741916337516
Best Equation: ((slip_de_biscaia_e_soares_2020 - eurocode_2) - sin(tensao_na_armadura_menos_tension_stiffening_variavel_mpa)) * 0.07809349



Train RMSE: 0.05466064554076318
Test RMSE: 0.06069175835159989
Train R2: 0.5903201652417687
Test R2: 0.6617635898792003

### Save data

In [9]:
base_filename = os.path.basename(filename).replace('.xlsx', '')  # 'dataset_1_rv3'
aux = [{'metadados': 'index [1] data of model trained fold=0 grid=0, index [2] data of model trained fold=0 grid=1, ...'}]
results = aux + dx
with open(f'results_pysr_model_8020_fib2020ts_{base_filename}.pkl', 'wb') as f:
    pickle.dump(results, f)