# Libraries

In [3]:
import pickle
import pandas as pd
pd.set_option('display.max_columns', None)

# Read dataset

In [5]:
from pathlib import Path
filename = Path('..') / 'train_symbolic_regression' / 'fib2020ts-dataset1' / 'results_pysr_model_8020_fib2020ts_dataset_1_rv3.pkl'
# filename = Path('..') / 'train_symbolic_regression' / 'fib2020ts-dataset2' / 'results_pysr_model_8020_fib2020ts_dataset_2_rv3.pkl'

with open(filename, 'rb') as f:
    df = pickle.load(f)
df

Detected IPython. Loading juliacall extension. See https://juliapy.github.io/PythonCall.jl/stable/compat/#IPython

[{'metadados': 'index [1] data of model trained fold=0 grid=0, index [2] data of model trained fold=0 grid=1, ...'},
 {'diametro_da_armadura_mm': {'avg': np.float64(17.79830882352941),
   'std_dev': np.float64(6.2643500032686195)},
  'resistencia_do_aco_fy_mpa': {'avg': np.float64(469.2610294117647),
   'std_dev': np.float64(103.90557907853743)},
  'numero_de_barras_em_uma_camada': {'avg': np.float64(2.5183823529411766),
   'std_dev': np.float64(1.3931398205810432)},
  'espacamento_entre_as_barras_mm': {'avg': np.float64(61.83496323529412),
   'std_dev': np.float64(47.3209057870668)},
  'resistencia_a_tracao_do_concreto_mpa': {'avg': np.float64(3.0870503126318427),
   'std_dev': np.float64(0.5062616665675194)},
  'cobrimento_mm': {'avg': np.float64(32.833970588235296),
   'std_dev': np.float64(10.850572279527592)},
  'distancia_ao_centro_de_gravidade_da_armadura_mm': {'avg': np.float64(43.95514705882353),
   'std_dev': np.float64(12.280465237480295)},
  'largura_da_viga_b_mm': {'avg': np.float64(198.80183823529413),
   'std_dev': np.float64(99.1676834717354)},
  'altura_da_viga_h_mm': {'avg': np.float64(343.16102941176473),
   'std_dev': np.float64(114.55370091384198)},
  'area_de_aco_tracionada_as_mm2': {'avg': np.float64(674.0871323529412),
   'std_dev': np.float64(580.2743753432611)},
  'momento_fletor_ms_knm': {'avg': np.float64(56.240933088235295),
   'std_dev': np.float64(60.913110118910666)},
  'fib_model_code_2010': {'avg': np.float64(0.21436819723601333),
   'std_dev': np.float64(0.08579464507916637)},
  'eurocode_2': {'avg': np.float64(0.22263636863283268),
   'std_dev': np.float64(0.0751451392594914)},
  'nbr_6118_wk1_fissuracao_estabilizada': {'avg': np.float64(0.2656494349516377),
   'std_dev': np.float64(0.07712256610635514)},
  'nbr_6118_wk2_fissuracao_nao_estabilizada': {'avg': np.float64(0.32059402022703143),
   'std_dev': np.float64(0.2031695829621887)},
  'clark_1956': {'avg': np.float64(0.225129020932907),
   'std_dev': np.float64(0.10338475383727401)},
  'desayiganesan_1985': {'avg': np.float64(0.27663986771691496),
   'std_dev': np.float64(0.0986891958615273)},
  'oh_kang_1987': {'avg': np.float64(0.27621302340487497),
   'std_dev': np.float64(0.08183875388593027)},
  'caldas_1997': {'avg': np.float64(0.20474213104572545),
   'std_dev': np.float64(0.08344736129611563)},
  'gergely_e_lutz_1968': {'avg': np.float64(0.27840095983446234),
   'std_dev': np.float64(0.07483729811582208)},
  'equacao_15_do_artigo_de_belarbi_e_hsu_1994': {'avg': np.float64(0.2736137363893007),
   'std_dev': np.float64(0.09182416297895885)},
  'beta_conforme_fields_e_bischoff_2004': {'avg': np.float64(0.27171774981023994),
   'std_dev': np.float64(0.11118748287483195)},
  'slip_de_yuan_et_al_2025': {'avg': np.float64(0.2779972425015701),
   'std_dev': np.float64(0.13323476000559695)},
  'slip_de_biscaia_e_soares_2020': {'avg': np.float64(0.24215945006590628),
   'std_dev': np.float64(0.11125854596883178)},
  'model': {'train_rmse': np.float64(0.05605128351573266),
   'test_rmse': np.float64(0.05099238909833682),
   'train_r2': 0.608389685140017,
   'test_r2': 0.6760349533894092,
   'best_equation': '-0.047367673 * (sin(espacamento_entre_as_barras_mm / -0.00056933786) + (eurocode_2 - momento_fletor_ms_knm))',
   'scaler_params': StandardScaler(),
   'model_object': PySRRegressor.equations_ = [
   	    pick     score                                           equation  \
   	0         0.000000                                       -0.004411577
   	1         0.166567        area_de_aco_tracionada_as_mm2 * 0.047880705
   	2         0.000300   sin(area_de_aco_tracionada_as_mm2 * 0.048038278)
   	3         0.299460  (eurocode_2 - momento_fletor_ms_knm) * -0.0462...
   	4         0.025868  ((diametro_da_armadura_mm + largura_da_viga_b_...
   	5         0.099428  (area_de_aco_tracionada_as_mm2 - (eurocode_2 /...
   	6         0.033906  (((1.17463 - momento_fletor_ms_knm) * eurocode...
   	7   >>>>  0.119520  -0.047367673 * (sin(espacamento_entre_as_barra...
   	8         0.004751  -0.05209459 * (sin(espacamento_entre_as_barras...
   	9         0.043611  (eurocode_2 + (sin((distancia_ao_centro_de_gra...
   	10        0.065297  (eurocode_2 + (cos(cobrimento_mm) - ((oh_kang_...
   	11        0.025117  ((eurocode_2 + sin(cos(cobrimento_mm))) - ((oh...
   	12        0.082148  ((eurocode_2 + cos(oh_kang_1987 - nbr_6118_wk1...
   	13        0.053169  (eurocode_2 + (sin(cos(nbr_6118_wk1_fissuracao...
   	14        0.016258  ((eurocode_2 + cos(distancia_ao_centro_de_grav...
   	15        0.041811  (eurocode_2 + (cos((beta_conforme_fields_e_bis...
   	16        0.000346  sin(((cos(nbr_6118_wk1_fissuracao_estabilizada...

   	        loss  complexity
   	0   0.008023           1
   	1   0.005750           3
   	2   0.005748           4
   	3   0.004260           5
   	4   0.004046           7
   	5   0.003663           8
   	6   0.003541           9
   	7   0.003142          10
   	8   0.003112          12
   	9   0.002979          13
   	10  0.002791          14
   	11  0.002722          15
   	12  0.002507          16
   	13  0.002377          17
   	14  0.002339          18
   	15  0.002243          19
   	16  0.002242          20
   ]}},
 {'diametro_da_armadura_mm': {'avg': np.float64(17.79830882352941),
   'std_dev': np.float64(6.2643500032686195)},
  'resistencia_do_aco_fy_mpa': {'avg': np.float64(469.2610294117647),
   'std_dev': np.float64(103.90557907853743)},
  'numero_de_barras_em_uma_camada': {'avg': np.float64(2.5183823529411766),
   'std_dev': np.float64(1.3931398205810432)},
  'espacamento_entre_as_barras_mm': {'avg': np.float64(61.83496323529412),
   'std_dev': np.float64(47.3209057870668)},
  'resistencia_a_tracao_do_concreto_mpa': {'avg': np.float64(3.0870503126318427),
   'std_dev': np.float64(0.5062616665675194)},
  'cobrimento_mm': {'avg': np.float64(32.833970588235296),
   'std_dev': np.float64(10.850572279527592)},
  'distancia_ao_centro_de_gravidade_da_armadura_mm': {'avg': np.float64(43.95514705882353),
   'std_dev': np.float64(12.280465237480295)},
  'largura_da_viga_b_mm': {'avg': np.float64(198.80183823529413),
   'std_dev': np.float64(99.1676834717354)},
  'altura_da_viga_h_mm': {'avg': np.float64(343.16102941176473),
   'std_dev': np.float64(114.55370091384198)},
  'area_de_aco_tracionada_as_mm2': {'avg': np.float64(674.0871323529412),
   'std_dev': np.float64(580.2743753432611)},
  'momento_fletor_ms_knm': {'avg': np.float64(56.240933088235295),
   'std_dev': np.float64(60.913110118910666)},
  'fib_model_code_2010': {'avg': np.float64(0.21436819723601333),
   'std_dev': np.float64(0.08579464507916637)},
  'eurocode_2': {'avg': np.float64(0.22263636863283268),
   'std_dev': np.float64(0.0751451392594914)},
  'nbr_6118_wk1_fissuracao_estabilizada': {'avg': np.float64(0.2656494349516377),
   'std_dev': np.float64(0.07712256610635514)},
  'nbr_6118_wk2_fissuracao_nao_estabilizada': {'avg': np.float64(0.32059402022703143),
   'std_dev': np.float64(0.2031695829621887)},
  'clark_1956': {'avg': np.float64(0.225129020932907),
   'std_dev': np.float64(0.10338475383727401)},
  'desayiganesan_1985': {'avg': np.float64(0.27663986771691496),
   'std_dev': np.float64(0.0986891958615273)},
  'oh_kang_1987': {'avg': np.float64(0.27621302340487497),
   'std_dev': np.float64(0.08183875388593027)},
  'caldas_1997': {'avg': np.float64(0.20474213104572545),
   'std_dev': np.float64(0.08344736129611563)},
  'gergely_e_lutz_1968': {'avg': np.float64(0.27840095983446234),
   'std_dev': np.float64(0.07483729811582208)},
  'equacao_15_do_artigo_de_belarbi_e_hsu_1994': {'avg': np.float64(0.2736137363893007),
   'std_dev': np.float64(0.09182416297895885)},
  'beta_conforme_fields_e_bischoff_2004': {'avg': np.float64(0.27171774981023994),
   'std_dev': np.float64(0.11118748287483195)},
  'slip_de_yuan_et_al_2025': {'avg': np.float64(0.2779972425015701),
   'std_dev': np.float64(0.13323476000559695)},
  'slip_de_biscaia_e_soares_2020': {'avg': np.float64(0.24215945006590628),
   'std_dev': np.float64(0.11125854596883178)},
  'model': {'train_rmse': np.float64(0.05950310930878914),
   'test_rmse': np.float64(0.05272522526281538),
   'train_r2': 0.5586711495919399,
   'test_r2': 0.6536427176514472,
   'best_equation': '(area_de_aco_tracionada_as_mm2 - (eurocode_2 * (1.1746627 - momento_fletor_ms_knm))) * 0.032086734',
   'scaler_params': StandardScaler(),
   'model_object': PySRRegressor.equations_ = [
   	    pick     score                                           equation  \
   	0         0.000000                                       -0.004411577
   	1         0.166567          area_de_aco_tracionada_as_mm2 * 0.0478807
   	2         0.000300   sin(area_de_aco_tracionada_as_mm2 * 0.048038308)
   	3         0.299460  (eurocode_2 - momento_fletor_ms_knm) * -0.0462...
   	4         0.025868  (diametro_da_armadura_mm - (eurocode_2 - largu...
   	5         0.022944  ((sin(largura_da_viga_b_mm) + momento_fletor_m...
   	6   >>>>  0.110390  (area_de_aco_tracionada_as_mm2 - (eurocode_2 *...
   	7         0.063014  ((eurocode_2 + sin(resistencia_do_aco_fy_mpa *...
   	8         0.018737  (eurocode_2 - (sin(cube(cube(resistencia_do_ac...
   	9         0.073988  (sin(square(area_de_aco_tracionada_as_mm2) + (...
   	10        0.047033  (momento_fletor_ms_knm + (sin(largura_da_viga_...
   	11        0.018443  (sin((distancia_ao_centro_de_gravidade_da_arma...
   	12        0.027179  (sin(cube(abs(area_de_aco_tracionada_as_mm2)) ...
   	13        0.035124  (sin(square(area_de_aco_tracionada_as_mm2) + (...
   	14        0.035183  (eurocode_2 - ((momento_fletor_ms_knm * cos(sq...
   	15        0.000308  sin((eurocode_2 - ((momento_fletor_ms_knm * co...
   	16        0.017059  (sin(cube(abs(area_de_aco_tracionada_as_mm2)) ...

   	        loss  complexity
   	0   0.008023           1
   	1   0.005750           3
   	2   0.005748           4
   	3   0.004260           5
   	4   0.004046           7
   	5   0.003954           8
   	6   0.003541           9
   	7   0.003324          10
   	8   0.003202          12
   	9   0.002974          13
   	10  0.002837          14
   	11  0.002785          15
   	12  0.002711          16
   	13  0.002617          17
   	14  0.002527          18
   	15  0.002526          19
   	16  0.002483          20
   ]}},
 {'diametro_da_armadura_mm': {'avg': np.float64(17.79830882352941),
   'std_dev': np.float64(6.2643500032686195)},
  'resistencia_do_aco_fy_mpa': {'avg': np.float64(469.2610294117647),
   'std_dev': np.float64(103.90557907853743)},
  'numero_de_barras_em_uma_camada': {'avg': np.float64(2.5183823529411766),
   'std_dev': np.float64(1.3931398205810432)},
  'espacamento_entre_as_barras_mm': {'avg': np.float64(61.83496323529412),
   'std_dev': np.float64(47.3209057870668)},
  'resistencia_a_tracao_do_concreto_mpa': {'avg': np.float64(3.0870503126318427),
   'std_dev': np.float64(0.5062616665675194)},
  'cobrimento_mm': {'avg': np.float64(32.833970588235296),
   'std_dev': np.float64(10.850572279527592)},
  'distancia_ao_centro_de_gravidade_da_armadura_mm': {'avg': np.float64(43.95514705882353),
   'std_dev': np.float64(12.280465237480295)},
  'largura_da_viga_b_mm': {'avg': np.float64(198.80183823529413),
   'std_dev': np.float64(99.1676834717354)},
  'altura_da_viga_h_mm': {'avg': np.float64(343.16102941176473),
   'std_dev': np.float64(114.55370091384198)},
  'area_de_aco_tracionada_as_mm2': {'avg': np.float64(674.0871323529412),
   'std_dev': np.float64(580.2743753432611)},
  'momento_fletor_ms_knm': {'avg': np.float64(56.240933088235295),
   'std_dev': np.float64(60.913110118910666)},
  'fib_model_code_2010': {'avg': np.float64(0.21436819723601333),
   'std_dev': np.float64(0.08579464507916637)},
  'eurocode_2': {'avg': np.float64(0.22263636863283268),
   'std_dev': np.float64(0.0751451392594914)},
  'nbr_6118_wk1_fissuracao_estabilizada': {'avg': np.float64(0.2656494349516377),
   'std_dev': np.float64(0.07712256610635514)},
  'nbr_6118_wk2_fissuracao_nao_estabilizada': {'avg': np.float64(0.32059402022703143),
   'std_dev': np.float64(0.2031695829621887)},
  'clark_1956': {'avg': np.float64(0.225129020932907),
   'std_dev': np.float64(0.10338475383727401)},
  'desayiganesan_1985': {'avg': np.float64(0.27663986771691496),
   'std_dev': np.float64(0.0986891958615273)},
  'oh_kang_1987': {'avg': np.float64(0.27621302340487497),
   'std_dev': np.float64(0.08183875388593027)},
  'caldas_1997': {'avg': np.float64(0.20474213104572545),
   'std_dev': np.float64(0.08344736129611563)},
  'gergely_e_lutz_1968': {'avg': np.float64(0.27840095983446234),
   'std_dev': np.float64(0.07483729811582208)},
  'equacao_15_do_artigo_de_belarbi_e_hsu_1994': {'avg': np.float64(0.2736137363893007),
   'std_dev': np.float64(0.09182416297895885)},
  'beta_conforme_fields_e_bischoff_2004': {'avg': np.float64(0.27171774981023994),
   'std_dev': np.float64(0.11118748287483195)},
  'slip_de_yuan_et_al_2025': {'avg': np.float64(0.2779972425015701),
   'std_dev': np.float64(0.13323476000559695)},
  'slip_de_biscaia_e_soares_2020': {'avg': np.float64(0.24215945006590628),
   'std_dev': np.float64(0.11125854596883178)},
  'model': {'train_rmse': np.float64(0.04801362316050787),
   'test_rmse': np.float64(0.04520299699501377),
   'train_r2': 0.7126494996796329,
   'test_r2': 0.745421399184624,
   'best_equation': '(((eurocode_2 * (momento_fletor_ms_knm - 1.2595336)) + diametro_da_armadura_mm) * 0.030218635) + (sin(largura_da_viga_b_mm + (numero_de_barras_em_uma_camada - cos(resistencia_a_tracao_do_concreto_mpa))) * 0.054154076)',
   'scaler_params': StandardScaler(),
   'model_object': PySRRegressor.equations_ = [
   	    pick     score                                           equation  \
   	0         0.000000                                         -0.0044115
   	1         0.166567        area_de_aco_tracionada_as_mm2 * 0.047880728
   	2         0.000300   sin(area_de_aco_tracionada_as_mm2 * 0.048038308)
   	3         0.299460  (momento_fletor_ms_knm - eurocode_2) * 0.04620918
   	4         0.025868  (eurocode_2 - (largura_da_viga_b_mm + diametro...
   	5         0.022944  (momento_fletor_ms_knm + (sin(largura_da_viga_...
   	6         0.110390  (area_de_aco_tracionada_as_mm2 + ((momento_fle...
   	7         0.063197  (momento_fletor_ms_knm + (sin(distancia_ao_cen...
   	8         0.062565  (sin(abs(area_de_aco_tracionada_as_mm2 / -3.86...
   	9         0.015656  ((cos(resistencia_do_aco_fy_mpa) * (sin(largur...
   	10        0.061781  ((area_de_aco_tracionada_as_mm2 + sin(largura_...
   	11        0.010993  ((area_de_aco_tracionada_as_mm2 + sin(0.825183...
   	12        0.021326  (diametro_da_armadura_mm + (sin((numero_de_bar...
   	13        0.064680  (sin(numero_de_barras_em_uma_camada + (largura...
   	14        0.013131  ((((momento_fletor_ms_knm - 1.287277) * euroco...
   	15  >>>>  0.100103  (((eurocode_2 * (momento_fletor_ms_knm - 1.259...
   	16        0.003565  ((diametro_da_armadura_mm + (eurocode_2 * (mom...
   	17        0.054319  ((eurocode_2 * (momento_fletor_ms_knm - 1.2271...
   	18        0.001450  sin((sin(largura_da_viga_b_mm + (numero_de_bar...
   	19        0.069466  (diametro_da_armadura_mm * 0.04294768) + ((sin...
   	20        0.002206  (sin(sin((numero_de_barras_em_uma_camada + lar...
   	21        0.003700  ((eurocode_2 + -0.09815013) * (-0.034056164 - ...
   	22        0.048476  (((eurocode_2 * 0.42955104) * (momento_fletor_...
   	23        0.004031  (eurocode_2 * (-0.039184652 - (momento_fletor_...
   	24        0.013872  (((sin((largura_da_viga_b_mm + numero_de_barra...
   	25        0.008773  ((diametro_da_armadura_mm + ((((momento_fletor...
   	26        0.006041  (((eurocode_2 * ((momento_fletor_ms_knm + sin(...

   	        loss  complexity
   	0   0.008023           1
   	1   0.005750           3
   	2   0.005748           4
   	3   0.004260           5
   	4   0.004046           7
   	5   0.003954           8
   	6   0.003541           9
   	7   0.003324          10
   	8   0.003122          11
   	9   0.003026          13
   	10  0.002845          14
   	11  0.002814          15
   	12  0.002754          16
   	13  0.002582          17
   	14  0.002548          18
   	15  0.002305          19
   	16  0.002297          20
   	17  0.002176          21
   	18  0.002173          22
   	19  0.002027          23
   	20  0.002022          24
   	21  0.002015          25
   	22  0.001919          26
   	23  0.001912          27
   	24  0.001885          28
   	25  0.001869          29
   	26  0.001858          30
   ]}},
 {'diametro_da_armadura_mm': {'avg': np.float64(17.79830882352941),
   'std_dev': np.float64(6.2643500032686195)},
  'resistencia_do_aco_fy_mpa': {'avg': np.float64(469.2610294117647),
   'std_dev': np.float64(103.90557907853743)},
  'numero_de_barras_em_uma_camada': {'avg': np.float64(2.5183823529411766),
   'std_dev': np.float64(1.3931398205810432)},
  'espacamento_entre_as_barras_mm': {'avg': np.float64(61.83496323529412),
   'std_dev': np.float64(47.3209057870668)},
  'resistencia_a_tracao_do_concreto_mpa': {'avg': np.float64(3.0870503126318427),
   'std_dev': np.float64(0.5062616665675194)},
  'cobrimento_mm': {'avg': np.float64(32.833970588235296),
   'std_dev': np.float64(10.850572279527592)},
  'distancia_ao_centro_de_gravidade_da_armadura_mm': {'avg': np.float64(43.95514705882353),
   'std_dev': np.float64(12.280465237480295)},
  'largura_da_viga_b_mm': {'avg': np.float64(198.80183823529413),
   'std_dev': np.float64(99.1676834717354)},
  'altura_da_viga_h_mm': {'avg': np.float64(343.16102941176473),
   'std_dev': np.float64(114.55370091384198)},
  'area_de_aco_tracionada_as_mm2': {'avg': np.float64(674.0871323529412),
   'std_dev': np.float64(580.2743753432611)},
  'momento_fletor_ms_knm': {'avg': np.float64(56.240933088235295),
   'std_dev': np.float64(60.913110118910666)},
  'fib_model_code_2010': {'avg': np.float64(0.21436819723601333),
   'std_dev': np.float64(0.08579464507916637)},
  'eurocode_2': {'avg': np.float64(0.22263636863283268),
   'std_dev': np.float64(0.0751451392594914)},
  'nbr_6118_wk1_fissuracao_estabilizada': {'avg': np.float64(0.2656494349516377),
   'std_dev': np.float64(0.07712256610635514)},
  'nbr_6118_wk2_fissuracao_nao_estabilizada': {'avg': np.float64(0.32059402022703143),
   'std_dev': np.float64(0.2031695829621887)},
  'clark_1956': {'avg': np.float64(0.225129020932907),
   'std_dev': np.float64(0.10338475383727401)},
  'desayiganesan_1985': {'avg': np.float64(0.27663986771691496),
   'std_dev': np.float64(0.0986891958615273)},
  'oh_kang_1987': {'avg': np.float64(0.27621302340487497),
   'std_dev': np.float64(0.08183875388593027)},
  'caldas_1997': {'avg': np.float64(0.20474213104572545),
   'std_dev': np.float64(0.08344736129611563)},
  'gergely_e_lutz_1968': {'avg': np.float64(0.27840095983446234),
   'std_dev': np.float64(0.07483729811582208)},
  'equacao_15_do_artigo_de_belarbi_e_hsu_1994': {'avg': np.float64(0.2736137363893007),
   'std_dev': np.float64(0.09182416297895885)},
  'beta_conforme_fields_e_bischoff_2004': {'avg': np.float64(0.27171774981023994),
   'std_dev': np.float64(0.11118748287483195)},
  'slip_de_yuan_et_al_2025': {'avg': np.float64(0.2779972425015701),
   'std_dev': np.float64(0.13323476000559695)},
  'slip_de_biscaia_e_soares_2020': {'avg': np.float64(0.24215945006590628),
   'std_dev': np.float64(0.11125854596883178)},
  'model': {'train_rmse': np.float64(0.050747101565941595),
   'test_rmse': np.float64(0.04287242992124996),
   'train_r2': 0.6789996666132156,
   'test_r2': 0.7709957017518295,
   'best_equation': '(beta_conforme_fields_e_bischoff_2004 - (cos(exp(distancia_ao_centro_de_gravidade_da_armadura_mm)) * (momento_fletor_ms_knm + (exp(sin(eurocode_2)) * largura_da_viga_b_mm)))) * -0.051693182',
   'scaler_params': StandardScaler(),
   'model_object': PySRRegressor.equations_ = [
   	    pick     score                                           equation  \

# Clean dataset

In [ ]:
df.columns

Index(['diametro_da_armadura_mm', 'resistencia_do_aco_fy_mpa',
       'resistencia_a_tracao_do_concreto_mpa', 'cobrimento_mm',
       'distancia_ao_centro_de_gravidade_da_armadura_mm',
       'area_de_aco_tracionada_as_mm2', 'taxa_de_armadura_conforme_mc2020',
       'tensao_na_armadura_menos_tension_stiffening_variavel_mpa',
       'fib_model_code_2010', 'eurocode_2',
       'nbr_6118_wk1_fissuracao_estabilizada',
       'nbr_6118_wk2_fissuracao_nao_estabilizada', 'clark_1956',
       'desayiganesan_1985', 'oh_kang_1987', 'caldas_1997',
       'gergely_e_lutz_1968', 'equacao_15_do_artigo_de_belarbi_e_hsu_1994',
       'beta_conforme_fields_e_bischoff_2004', 'slip_de_yuan_et_al_2025',
       'slip_de_biscaia_e_soares_2020'],
      dtype='object')

In [ ]:
eliminated_columns = [
                        'fib_model_code_2010', 'eurocode_2',
                        'nbr_6118_wk1_fissuracao_estabilizada',
                        'nbr_6118_wk2_fissuracao_nao_estabilizada', 'clark_1956',
                        'desayiganesan_1985', 'oh_kang_1987', 'caldas_1997',
                        'gergely_e_lutz_1968', 'equacao_15_do_artigo_de_belarbi_e_hsu_1994',
                        'beta_conforme_fields_e_bischoff_2004', 'slip_de_yuan_et_al_2025',
                        'slip_de_biscaia_e_soares_2020'
                    ]

In [ ]:
df.drop(eliminated_columns, inplace=True, axis=1)
df.head()

,diametro_da_armadura_mm,resistencia_do_aco_fy_mpa,resistencia_a_tracao_do_concreto_mpa,cobrimento_mm,distancia_ao_centro_de_gravidade_da_armadura_mm,area_de_aco_tracionada_as_mm2,taxa_de_armadura_conforme_mc2020,tensao_na_armadura_menos_tension_stiffening_variavel_mpa
0,20.0,500,4.120341,25.0,39.0,628.0,0.0213,120.527746
1,20.0,500,4.120341,25.0,39.0,628.0,0.0213,223.847983
2,20.0,500,4.120341,25.0,39.0,628.0,0.0213,242.052198
3,20.0,500,4.120341,25.0,39.0,628.0,0.0213,325.147190
4,20.0,500,4.120341,25.0,39.0,628.0,0.0213,447.784457

# Dataset statistics

In [ ]:
df_x = df.describe().T
df_x.drop(columns=["count", "25%", "50%", "75%"], inplace=True)
df_x

,mean,std,min,max
diametro_da_armadura_mm,17.881056,6.258067,9.520000,35.800000
resistencia_do_aco_fy_mpa,468.002933,102.262652,276.000000,628.000000
resistencia_a_tracao_do_concreto_mpa,3.090431,0.501076,2.384602,5.308474
cobrimento_mm,32.846188,10.776445,12.800000,70.000000
distancia_ao_centro_de_gravidade_da_armadura_mm,43.834604,12.213950,23.900000,94.500000
area_de_aco_tracionada_as_mm2,680.651320,585.507137,78.500000,2826.000000
taxa_de_armadura_conforme_mc2020,0.025807,0.015466,0.008263,0.079968
tensao_na_armadura_menos_tension_stiffening_variavel_mpa,244.690914,119.278613,0.000000,628.000000

In [ ]:
df_x_latex = df_x.copy()
df_x_latex.columns = [str(c).replace("_", " ") for c in df_x_latex.columns]
df_x_latex.index = [str(i).replace("_", " ") for i in df_x_latex.index]

latex_table = df_x_latex.to_latex(
    index=True,
    float_format="%.2f",
    caption="Descriptive statistics of Dataset 1.",
    label="tab:dataset_1_stats_summary",
    longtable=False,
    escape=False
)

print(latex_table)

\begin{table}
\caption{Descriptive statistics of Dataset 1.}
\label{tab:dataset_1_stats_summary}
\begin{tabular}{lrrrr}
\toprule
 & mean & std & min & max \\
\midrule
diametro da armadura mm & 17.88 & 6.26 & 9.52 & 35.80 \\
resistencia do aco fy mpa & 468.00 & 102.26 & 276.00 & 628.00 \\
resistencia a tracao do concreto mpa & 3.09 & 0.50 & 2.38 & 5.31 \\
cobrimento mm & 32.85 & 10.78 & 12.80 & 70.00 \\
distancia ao centro de gravidade da armadura mm & 43.83 & 12.21 & 23.90 & 94.50 \\
area de aco tracionada as mm2 & 680.65 & 585.51 & 78.50 & 2826.00 \\
taxa de armadura conforme mc2020 & 0.03 & 0.02 & 0.01 & 0.08 \\
tensao na armadura menos tension stiffening variavel mpa & 244.69 & 119.28 & 0.00 & 628.00 \\
\bottomrule
\end{tabular}
\end{table}