# Libraries

In [27]:
import pickle
import pandas as pd
pd.set_option('display.max_columns', None)

# Read dataset

In [ ]:
# filename = 'z_dataset_1_wexp_menos_wfib2020.pkl'
filename = 'z_dataset_2_wexp_menos_wfib2020.pkl'
df = pickle.load(open(filename, 'rb'))
df = df[1]
df

,diametro_da_armadura_mm,resistencia_do_aco_fy_mpa,resistencia_a_tracao_do_concreto_mpa,cobrimento_mm,distancia_ao_centro_de_gravidade_da_armadura_mm,area_de_aco_tracionada_as_mm2,taxa_de_armadura_conforme_mc2020,tensao_na_armadura_menos_tension_stiffening_variavel_mpa,fib_model_code_2010,eurocode_2,nbr_6118_wk1_fissuracao_estabilizada,nbr_6118_wk2_fissuracao_nao_estabilizada,clark_1956,desayiganesan_1985,oh_kang_1987,caldas_1997,gergely_e_lutz_1968,equacao_15_do_artigo_de_belarbi_e_hsu_1994,beta_conforme_fields_e_bischoff_2004,slip_de_yuan_et_al_2025,slip_de_biscaia_e_soares_2020
0,20.0,500,4.120341,25.0,39.0,628.0,0.021300,120.527746,0.125734,0.125292,0.262468,0.157380,0.181006,0.312684,0.185969,0.129998,0.241528,0.149956,0.116566,0.109686,0.082007
1,20.0,500,4.120341,25.0,39.0,628.0,0.021300,223.847983,0.176982,0.176359,0.344489,0.271111,0.244363,0.410398,0.256204,0.174746,0.317005,0.204348,0.197288,0.193326,0.156266
2,20.0,500,4.120341,25.0,39.0,628.0,0.021300,242.052198,0.184078,0.183430,0.355846,0.289281,0.253135,0.423928,0.265928,0.180941,0.327456,0.212052,0.208041,0.205301,0.167096
3,20.0,500,4.120341,25.0,39.0,628.0,0.021300,325.147190,0.218769,0.217999,0.411368,0.386596,0.296022,0.490072,0.313472,0.211232,0.378549,0.250139,0.259368,0.265222,0.221958
4,20.0,500,4.120341,25.0,39.0,628.0,0.021300,447.784457,0.286574,0.285566,0.519888,0.617471,0.379848,0.619355,0.406398,0.270437,0.478411,0.311870,0.354810,0.388948,0.338382
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336,28.7,276,2.576579,38.0,52.3,1290.0,0.046242,213.143867,0.211435,0.217883,0.227172,0.402373,0.127495,0.137933,0.211920,0.208132,0.235766,0.238556,0.233751,0.326560,0.266684
337,28.7,276,2.576579,38.0,52.3,1290.0,0.046242,245.038321,0.238730,0.246011,0.240743,0.451883,0.143467,0.153289,0.240046,0.233354,0.262014,0.247400,0.266497,0.378289,0.310953
338,35.8,276,2.547836,38.0,55.9,2012.0,0.067478,150.918822,0.131534,0.146640,0.176752,0.281743,0.081715,0.101441,0.160100,0.154484,0.187961,0.165331,0.155387,0.253458,0.182233
339,35.8,276,2.756373,38.0,55.9,2012.0,0.067478,108.349173,0.097515,0.108471,0.138397,0.159666,0.061803,0.083394,0.115350,0.116635,0.146565,0.125892,0.108061,0.170128,0.122579
340,35.8,276,2.756373,38.0,55.9,2012.0,0.067478,148.199287,0.130443,0.145098,0.176752,0.260428,0.081496,0.106506,0.159637,0.154068,0.187184,0.163974,0.152755,0.242783,0.176480

# Clean dataset

In [29]:
df.columns

Index(['diametro_da_armadura_mm', 'resistencia_do_aco_fy_mpa',
       'resistencia_a_tracao_do_concreto_mpa', 'cobrimento_mm',
       'distancia_ao_centro_de_gravidade_da_armadura_mm',
       'area_de_aco_tracionada_as_mm2', 'taxa_de_armadura_conforme_mc2020',
       'tensao_na_armadura_menos_tension_stiffening_variavel_mpa',
       'fib_model_code_2010', 'eurocode_2',
       'nbr_6118_wk1_fissuracao_estabilizada',
       'nbr_6118_wk2_fissuracao_nao_estabilizada', 'clark_1956',
       'desayiganesan_1985', 'oh_kang_1987', 'caldas_1997',
       'gergely_e_lutz_1968', 'equacao_15_do_artigo_de_belarbi_e_hsu_1994',
       'beta_conforme_fields_e_bischoff_2004', 'slip_de_yuan_et_al_2025',
       'slip_de_biscaia_e_soares_2020'],
      dtype='object')

In [30]:
eliminated_columns = [
                        'fib_model_code_2010', 'eurocode_2',
                        'nbr_6118_wk1_fissuracao_estabilizada',
                        'nbr_6118_wk2_fissuracao_nao_estabilizada', 'clark_1956',
                        'desayiganesan_1985', 'oh_kang_1987', 'caldas_1997',
                        'gergely_e_lutz_1968', 'equacao_15_do_artigo_de_belarbi_e_hsu_1994',
                        'beta_conforme_fields_e_bischoff_2004', 'slip_de_yuan_et_al_2025',
                        'slip_de_biscaia_e_soares_2020'
                    ]

In [31]:
df.drop(eliminated_columns, inplace=True, axis=1)
df.head()

,diametro_da_armadura_mm,resistencia_do_aco_fy_mpa,resistencia_a_tracao_do_concreto_mpa,cobrimento_mm,distancia_ao_centro_de_gravidade_da_armadura_mm,area_de_aco_tracionada_as_mm2,taxa_de_armadura_conforme_mc2020,tensao_na_armadura_menos_tension_stiffening_variavel_mpa
0,20.0,500,4.120341,25.0,39.0,628.0,0.0213,120.527746
1,20.0,500,4.120341,25.0,39.0,628.0,0.0213,223.847983
2,20.0,500,4.120341,25.0,39.0,628.0,0.0213,242.052198
3,20.0,500,4.120341,25.0,39.0,628.0,0.0213,325.147190
4,20.0,500,4.120341,25.0,39.0,628.0,0.0213,447.784457

# Dataset statistics

In [32]:
df_x = df.describe().T
df_x.drop(columns=["count", "25%", "50%", "75%"], inplace=True)
df_x

,mean,std,min,max
diametro_da_armadura_mm,17.881056,6.258067,9.520000,35.800000
resistencia_do_aco_fy_mpa,468.002933,102.262652,276.000000,628.000000
resistencia_a_tracao_do_concreto_mpa,3.090431,0.501076,2.384602,5.308474
cobrimento_mm,32.846188,10.776445,12.800000,70.000000
distancia_ao_centro_de_gravidade_da_armadura_mm,43.834604,12.213950,23.900000,94.500000
area_de_aco_tracionada_as_mm2,680.651320,585.507137,78.500000,2826.000000
taxa_de_armadura_conforme_mc2020,0.025807,0.015466,0.008263,0.079968
tensao_na_armadura_menos_tension_stiffening_variavel_mpa,244.690914,119.278613,0.000000,628.000000

In [33]:
df_x_latex = df_x.copy()
df_x_latex.columns = [str(c).replace("_", " ") for c in df_x_latex.columns]
df_x_latex.index = [str(i).replace("_", " ") for i in df_x_latex.index]

latex_table = df_x_latex.to_latex(
    index=True,
    float_format="%.2f",
    caption="Descriptive statistics of Dataset 1.",
    label="tab:dataset_1_stats_summary",
    longtable=False,
    escape=False
)

print(latex_table)

\begin{table}
\caption{Descriptive statistics of Dataset 1.}
\label{tab:dataset_1_stats_summary}
\begin{tabular}{lrrrr}
\toprule
 & mean & std & min & max \\
\midrule
diametro da armadura mm & 17.88 & 6.26 & 9.52 & 35.80 \\
resistencia do aco fy mpa & 468.00 & 102.26 & 276.00 & 628.00 \\
resistencia a tracao do concreto mpa & 3.09 & 0.50 & 2.38 & 5.31 \\
cobrimento mm & 32.85 & 10.78 & 12.80 & 70.00 \\
distancia ao centro de gravidade da armadura mm & 43.83 & 12.21 & 23.90 & 94.50 \\
area de aco tracionada as mm2 & 680.65 & 585.51 & 78.50 & 2826.00 \\
taxa de armadura conforme mc2020 & 0.03 & 0.02 & 0.01 & 0.08 \\
tensao na armadura menos tension stiffening variavel mpa & 244.69 & 119.28 & 0.00 & 628.00 \\
\bottomrule
\end{tabular}
\end{table}